# name: Beta

# on:
#   push:
#     branches: [ main, dev ]
#   pull_request:
#   workflow_dispatch:

# jobs:
#   build-beta:

#     runs-on: macOS-11
#     env:
#       DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: make build
#     - name: Run tests
#       run: make test
